package forms;

import camaraApi.Capi;
import camaraApi.Deputado;
import camaraApi.Discurso;
import java.awt.Color;
import java.awt.Image;
import banco.BancoUsuarios;
import banco.Usuario;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONException;

/**
 *
 * @author lucas
 */
public class Politicos extends javax.swing.JFrame {

    Usuario usuario;

    /**
     * Creates new form Home15
     */
    public Politicos(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        imprimirMinhaConta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radPesquisa = new javax.swing.ButtonGroup();
        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        subtitulo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JLabel();
        btnMinhaConta = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JLabel();
        Principal = new javax.swing.JPanel();
        Usuarios = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        btnPesquisarUsuario = new javax.swing.JButton();
        MostraUsuario = new javax.swing.JPanel();
        body_mostradeputado4 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        lblEmail4 = new javax.swing.JLabel();
        lblIL4 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtNome10 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtNome11 = new javax.swing.JTextField();
        txtNome13 = new javax.swing.JTextField();
        txtNome14 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDeputado3 = new javax.swing.JTable();
        btnPesquisarDeputado3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        btnLogin4 = new javax.swing.JLabel();
        btnLogin5 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        btnLogin8 = new javax.swing.JLabel();
        MostraDeputado = new javax.swing.JPanel();
        body_mostradeputado = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiscurso = new javax.swing.JTextArea();
        lblUf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblIL = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblPartido = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblEscolaridade = new javax.swing.JLabel();
        btnFavoritar = new javax.swing.JLabel();
        Deputados = new javax.swing.JPanel();
        body_pesquisa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeputado = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        btnPesquisarDeputado = new javax.swing.JButton();
        MinhaConta = new javax.swing.JPanel();
        body_mostradeputado5 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        lblEmail5 = new javax.swing.JLabel();
        lblIL5 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdeologia = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblDeputado4 = new javax.swing.JTable();
        btnPesquisarDeputado4 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        btnMudarSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setPreferredSize(new java.awt.Dimension(838, 200));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        subtitulo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        subtitulo.setForeground(new java.awt.Color(255, 255, 255));
        subtitulo.setText("Informações sobre os deputados federais");

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Políticos");

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        btnPesquisa.setBackground(new java.awt.Color(0, 153, 153));
        btnPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPesquisa.setText("Pesquisa");
        btnPesquisa.setOpaque(true);
        btnPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisaMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        btnVoltar.setBackground(new java.awt.Color(0, 153, 153));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVoltar.setText("<");
        btnVoltar.setOpaque(true);
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });

        btnMinhaConta.setBackground(new java.awt.Color(0, 153, 153));
        btnMinhaConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMinhaConta.setForeground(new java.awt.Color(255, 255, 255));
        btnMinhaConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinhaConta.setText("Minha Conta");
        btnMinhaConta.setOpaque(true);
        btnMinhaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinhaContaMouseClicked(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(0, 153, 153));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setText("Usuários");
        btnUsuarios.setOpaque(true);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subtitulo))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(btnMinhaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnVoltar))
                        .addGap(27, 27, 27))
                    .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(subtitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinhaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );

        btnPesquisa.getAccessibleContext().setAccessibleName("Políticos");

        Principal.setLayout(new java.awt.CardLayout());

        Usuarios.setBackground(new java.awt.Color(243, 243, 243));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);

        tblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Cpf", "Senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuario.setGridColor(new java.awt.Color(255, 255, 255));
        tblUsuario.setRowHeight(20);
        tblUsuario.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblUsuario);
        if (tblUsuario.getColumnModel().getColumnCount() > 0) {
            tblUsuario.getColumnModel().getColumn(0).setResizable(false);
            tblUsuario.getColumnModel().getColumn(1).setResizable(false);
            tblUsuario.getColumnModel().getColumn(2).setResizable(false);
            tblUsuario.getColumnModel().getColumn(3).setResizable(false);
        }

        jTextField3.setToolTipText("Pesquisar");

        btnPesquisarUsuario.setText("Pesquisar");
        btnPesquisarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarUsuarioMouseClicked(evt);
            }
        });
        btnPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsuariosLayout = new javax.swing.GroupLayout(Usuarios);
        Usuarios.setLayout(UsuariosLayout);
        UsuariosLayout.setHorizontalGroup(
            UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
            .addGroup(UsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisarUsuario)
                .addGap(8, 8, 8))
        );
        UsuariosLayout.setVerticalGroup(
            UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariosLayout.createSequentialGroup()
                .addGroup(UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarUsuario))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        Principal.add(Usuarios, "card3");

        MostraUsuario.setBackground(new java.awt.Color(255, 255, 255));
        MostraUsuario.setPreferredSize(new java.awt.Dimension(450, 450));
        MostraUsuario.setLayout(new javax.swing.BoxLayout(MostraUsuario, javax.swing.BoxLayout.LINE_AXIS));

        body_mostradeputado4.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel35.setText("Email:");

        lblEmail4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblEmail4.setText(" ");

        lblIL4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblIL4.setText(" ");

        jLabel36.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel36.setText("Id Legislatura:");

        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel37.setText("Ideologia:");

        jLabel38.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel38.setText("CPF: ");

        txtNome10.setBackground(new java.awt.Color(240, 240, 240));
        txtNome10.setFont(new java.awt.Font("Raleway Light", 0, 16)); // NOI18N
        txtNome10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        txtNome10.setSelectionColor(new java.awt.Color(0, 153, 153));

        jLabel40.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel40.setText("Nome:");

        txtNome11.setBackground(new java.awt.Color(240, 240, 240));
        txtNome11.setFont(new java.awt.Font("Raleway Light", 0, 16)); // NOI18N
        txtNome11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        txtNome11.setSelectionColor(new java.awt.Color(0, 153, 153));

        txtNome13.setBackground(new java.awt.Color(240, 240, 240));
        txtNome13.setFont(new java.awt.Font("Raleway Light", 0, 16)); // NOI18N
        txtNome13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        txtNome13.setSelectionColor(new java.awt.Color(0, 153, 153));
        txtNome13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome13ActionPerformed(evt);
            }
        });

        txtNome14.setBackground(new java.awt.Color(240, 240, 240));
        txtNome14.setFont(new java.awt.Font("Raleway Light", 0, 16)); // NOI18N
        txtNome14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        txtNome14.setSelectionColor(new java.awt.Color(0, 153, 153));

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);

        tblDeputado3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblDeputado3.setForeground(new java.awt.Color(51, 51, 51));
        tblDeputado3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Partido", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDeputado3.setGridColor(new java.awt.Color(255, 255, 255));
        tblDeputado3.setRowHeight(20);
        tblDeputado3.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblDeputado3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeputado3MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblDeputado3);
        if (tblDeputado3.getColumnModel().getColumnCount() > 0) {
            tblDeputado3.getColumnModel().getColumn(0).setResizable(false);
            tblDeputado3.getColumnModel().getColumn(1).setResizable(false);
            tblDeputado3.getColumnModel().getColumn(2).setResizable(false);
            tblDeputado3.getColumnModel().getColumn(3).setResizable(false);
        }

        btnPesquisarDeputado3.setText("Pesquisar");
        btnPesquisarDeputado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarDeputado3ActionPerformed(evt);
            }
        });

        jTextField5.setToolTipText("Pesquisar");

        btnLogin4.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLogin4.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin4.setText("Salvar");
        btnLogin4.setOpaque(true);
        btnLogin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogin4MouseClicked(evt);
            }
        });

        btnLogin5.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLogin5.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin5.setText("Excluir");
        btnLogin5.setOpaque(true);
        btnLogin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogin5MouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel41.setText("Políticos Favoritos:");

        btnLogin8.setBackground(new java.awt.Color(0, 204, 153));
        btnLogin8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLogin8.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin8.setText("Modificar Senha");
        btnLogin8.setOpaque(true);
        btnLogin8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogin8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout body_mostradeputado4Layout = new javax.swing.GroupLayout(body_mostradeputado4);
        body_mostradeputado4.setLayout(body_mostradeputado4Layout);
        body_mostradeputado4Layout.setHorizontalGroup(
            body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIL4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                                .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogin5, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(lblEmail4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(29, 29, 29)
                                .addComponent(txtNome11, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)
                        .addGap(34, 34, 34)
                        .addComponent(txtNome10, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome13)
                            .addComponent(txtNome14, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogin8, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(0, 423, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_mostradeputado4Layout.createSequentialGroup()
                        .addComponent(jTextField5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarDeputado3)
                        .addContainerGap())
                    .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addGap(11, 11, 11))))
        );
        body_mostradeputado4Layout.setVerticalGroup(
            body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPesquisarDeputado3)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_mostradeputado4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtNome11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                        .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtNome10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(lblEmail4))
                            .addGroup(body_mostradeputado4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(txtNome13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel38)
                                    .addComponent(txtNome14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnLogin4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(body_mostradeputado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(lblIL4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MostraUsuario.add(body_mostradeputado4);

        Principal.add(MostraUsuario, "card3");

        MostraDeputado.setBackground(new java.awt.Color(255, 255, 255));
        MostraDeputado.setPreferredSize(new java.awt.Dimension(450, 450));
        MostraDeputado.setLayout(new javax.swing.BoxLayout(MostraDeputado, javax.swing.BoxLayout.LINE_AXIS));

        body_mostradeputado.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        lblImg.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        txtDiscurso.setEditable(false);
        txtDiscurso.setColumns(20);
        txtDiscurso.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        txtDiscurso.setLineWrap(true);
        txtDiscurso.setRows(5);
        txtDiscurso.setWrapStyleWord(true);
        txtDiscurso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(txtDiscurso);

        lblUf.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUf.setText(" ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Unidade Federativa:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Email:");

        lblEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblEmail.setText(" ");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Escolaridade: ");

        lblCpf.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblCpf.setText(" ");

        lblIL.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblIL.setText(" ");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setText("Id Legislatura:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Cidade:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("Partido:");

        lblCidade.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblCidade.setText(" ");

        lblPartido.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPartido.setText(" ");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setText("CPF: ");

        lblEscolaridade.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblEscolaridade.setText(" ");

        btnFavoritar.setBackground(new java.awt.Color(0, 153, 153));
        btnFavoritar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnFavoritar.setForeground(new java.awt.Color(255, 255, 255));
        btnFavoritar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFavoritar.setText("Favoritar");
        btnFavoritar.setOpaque(true);
        btnFavoritar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFavoritarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout body_mostradeputadoLayout = new javax.swing.GroupLayout(body_mostradeputado);
        body_mostradeputado.setLayout(body_mostradeputadoLayout);
        body_mostradeputadoLayout.setHorizontalGroup(
            body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                        .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFavoritar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );
        body_mostradeputadoLayout.setVerticalGroup(
            body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblEscolaridade))
                .addGap(2, 2, 2)
                .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUf))
                .addGap(4, 4, 4)
                .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblPartido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_mostradeputadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblIL))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(body_mostradeputadoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFavoritar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MostraDeputado.add(body_mostradeputado);

        Principal.add(MostraDeputado, "card3");

        Deputados.setBackground(new java.awt.Color(255, 255, 255));
        Deputados.setPreferredSize(new java.awt.Dimension(450, 450));
        Deputados.setLayout(new javax.swing.BoxLayout(Deputados, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tblDeputado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblDeputado.setForeground(new java.awt.Color(51, 51, 51));
        tblDeputado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Partido", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDeputado.setGridColor(new java.awt.Color(255, 255, 255));
        tblDeputado.setRowHeight(20);
        tblDeputado.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblDeputado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeputadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDeputado);
        if (tblDeputado.getColumnModel().getColumnCount() > 0) {
            tblDeputado.getColumnModel().getColumn(0).setResizable(false);
            tblDeputado.getColumnModel().getColumn(1).setResizable(false);
            tblDeputado.getColumnModel().getColumn(2).setResizable(false);
            tblDeputado.getColumnModel().getColumn(3).setResizable(false);
        }

        radPesquisa.add(jRadioButton1);
        jRadioButton1.setText("Nome");

        radPesquisa.add(jRadioButton2);
        jRadioButton2.setText("Id");

        radPesquisa.add(jRadioButton3);
        jRadioButton3.setText("Partido");

        jTextField1.setToolTipText("Pesquisar");

        btnPesquisarDeputado.setText("Pesquisar");
        btnPesquisarDeputado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarDeputadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout body_pesquisaLayout = new javax.swing.GroupLayout(body_pesquisa);
        body_pesquisa.setLayout(body_pesquisaLayout);
        body_pesquisaLayout.setHorizontalGroup(
            body_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
            .addGroup(body_pesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(body_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_pesquisaLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(body_pesquisaLayout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarDeputado)))
                .addContainerGap())
        );
        body_pesquisaLayout.setVerticalGroup(
            body_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_pesquisaLayout.createSequentialGroup()
                .addGroup(body_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarDeputado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        Deputados.add(body_pesquisa);

        Principal.add(Deputados, "card3");

        MinhaConta.setBackground(new java.awt.Color(255, 255, 255));
        MinhaConta.setPreferredSize(new java.awt.Dimension(450, 450));
        MinhaConta.setLayout(new javax.swing.BoxLayout(MinhaConta, javax.swing.BoxLayout.LINE_AXIS));

        body_mostradeputado5.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N

        jLabel42.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel42.setText("Email:");

        lblEmail5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblEmail5.setText(" ");

        lblIL5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblIL5.setText(" ");

        jLabel43.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel43.setText("Id Legislatura:");

        jLabel44.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel44.setText("Ideologia:");

        jLabel45.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel45.setText("CPF: ");

        txtEmail.setBackground(new java.awt.Color(240, 240, 240));
        txtEmail.setFont(new java.awt.Font("Raleway Light", 0, 16)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        txtEmail.setSelectionColor(new java.awt.Color(0, 153, 153));

        jLabel47.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel47.setText("Nome:");

        txtNome.setBackground(new java.awt.Color(240, 240, 240));
        txtNome.setFont(new java.awt.Font("Raleway Light", 0, 16)); // NOI18N
        txtNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        txtNome.setSelectionColor(new java.awt.Color(0, 153, 153));

        txtIdeologia.setBackground(new java.awt.Color(240, 240, 240));
        txtIdeologia.setFont(new java.awt.Font("Raleway Light", 0, 16)); // NOI18N
        txtIdeologia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        txtIdeologia.setSelectionColor(new java.awt.Color(0, 153, 153));
        txtIdeologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdeologiaActionPerformed(evt);
            }
        });

        txtCPF.setBackground(new java.awt.Color(240, 240, 240));
        txtCPF.setFont(new java.awt.Font("Raleway Light", 0, 16)); // NOI18N
        txtCPF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 153)));
        txtCPF.setSelectionColor(new java.awt.Color(0, 153, 153));

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(null);

        tblDeputado4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblDeputado4.setForeground(new java.awt.Color(51, 51, 51));
        tblDeputado4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Partido", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDeputado4.setGridColor(new java.awt.Color(255, 255, 255));
        tblDeputado4.setRowHeight(20);
        tblDeputado4.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblDeputado4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeputado4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblDeputado4);
        if (tblDeputado4.getColumnModel().getColumnCount() > 0) {
            tblDeputado4.getColumnModel().getColumn(0).setResizable(false);
            tblDeputado4.getColumnModel().getColumn(1).setResizable(false);
            tblDeputado4.getColumnModel().getColumn(2).setResizable(false);
            tblDeputado4.getColumnModel().getColumn(3).setResizable(false);
        }

        btnPesquisarDeputado4.setText("Pesquisar");
        btnPesquisarDeputado4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarDeputado4MouseClicked(evt);
            }
        });
        btnPesquisarDeputado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarDeputado4ActionPerformed(evt);
            }
        });

        jTextField6.setToolTipText("Pesquisar");

        btnAlterar.setBackground(new java.awt.Color(0, 153, 153));
        btnAlterar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAlterar.setText("Salvar");
        btnAlterar.setOpaque(true);
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(0, 153, 153));
        btnExcluir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExcluir.setText("Excluir");
        btnExcluir.setOpaque(true);
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel48.setText("Políticos Favoritos:");

        btnMudarSenha.setBackground(new java.awt.Color(0, 153, 153));
        btnMudarSenha.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnMudarSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnMudarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMudarSenha.setText("Modificar Senha");
        btnMudarSenha.setOpaque(true);
        btnMudarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMudarSenhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout body_mostradeputado5Layout = new javax.swing.GroupLayout(body_mostradeputado5);
        body_mostradeputado5.setLayout(body_mostradeputado5Layout);
        body_mostradeputado5Layout.setHorizontalGroup(
            body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIL5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                                .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(lblEmail5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(29, 29, 29)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                                .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel45))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdeologia)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(34, 34, 34)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnMudarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(0, 423, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_mostradeputado5Layout.createSequentialGroup()
                        .addComponent(jTextField6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarDeputado4)
                        .addContainerGap())
                    .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                        .addComponent(jScrollPane7)
                        .addGap(11, 11, 11))))
        );
        body_mostradeputado5Layout.setVerticalGroup(
            body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPesquisarDeputado4)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_mostradeputado5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblEmail5))
                    .addGroup(body_mostradeputado5Layout.createSequentialGroup()
                        .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txtIdeologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMudarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(body_mostradeputado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(lblIL5))
                .addGap(0, 119, Short.MAX_VALUE))
        );

        MinhaConta.add(body_mostradeputado5);

        Principal.add(MinhaConta, "card3");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx;
    int xy;
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();

    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_headerMouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaMouseClicked
        // TODO add your handling code here:
        setLblColor(btnPesquisa);
        resetLblColor(btnMinhaConta);
        resetLblColor(btnUsuarios);
        limpaTela();
        Deputados.setVisible(true);

    }//GEN-LAST:event_btnPesquisaMouseClicked

    private void btnPesquisarDeputadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarDeputadoActionPerformed
        try {
            String pesquisa = jTextField1.getText();
            imprimirDeputados(pesquisa);

        } catch (JSONException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarDeputadoActionPerformed

    private void tblDeputadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeputadoMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDeputado.getModel();
        int selectedRowIndex = tblDeputado.getSelectedRow();
        String id_deputado = model.getValueAt(selectedRowIndex, 0).toString();

        limpaTela();
        MostraDeputado.setVisible(true);
        btnPesquisa.setVisible(false);
        btnUsuarios.setVisible(false);
        btnMinhaConta.setVisible(false);
        btnVoltar.setVisible(true);
        txtDiscurso.setText("");

        try {
            imprimirSelecao(id_deputado);
        } catch (JSONException ex) {
            Logger.getLogger(Politicos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tblDeputadoMouseClicked

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        setLblColor(btnMinhaConta);
        resetLblColor(btnPesquisa);
        limpaTela();
        MinhaConta.setVisible(true);
        btnVoltar.setVisible(false);
        btnPesquisa.setVisible(true);
        btnUsuarios.setVisible(true);
        btnMinhaConta.setVisible(true);
        titulo.setText("Políticos");
        subtitulo.setText("Informações sobre os deputados federais");
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnMinhaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinhaContaMouseClicked
        setLblColor(btnMinhaConta);
        resetLblColor(btnPesquisa);
        resetLblColor(btnUsuarios);
        limpaTela();

        this.txtNome.setText(usuario.getNome());
        this.txtEmail.setText(usuario.getEmail());
        this.txtCPF.setText(usuario.getCpf());
        this.txtIdeologia.setText(usuario.getIdeologia());
        //this.txtSenha.setText(usuario.getSenha());

        MinhaConta.setVisible(true);
    }//GEN-LAST:event_btnMinhaContaMouseClicked

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        setLblColor(btnUsuarios);
        resetLblColor(btnPesquisa);
        resetLblColor(btnMinhaConta);
        limpaTela();
        Usuarios.setVisible(true);
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnVoltar.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblUsuario.getModel();
        int selectedRowIndex = tblUsuario.getSelectedRow();
        String id_deputado = model.getValueAt(selectedRowIndex, 0).toString();

        limpaTela();
        btnPesquisa.setVisible(false);
        btnUsuarios.setVisible(false);
        btnMinhaConta.setVisible(false);
        btnVoltar.setVisible(true);
        MostraUsuario.setVisible(true);
        txtDiscurso.setText("");

        try {
            imprimirSelecao(id_deputado);
        } catch (JSONException ex) {
            Logger.getLogger(Politicos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void btnPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarUsuarioActionPerformed

    private void btnPesquisarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarUsuarioMouseClicked
        this.imprimirUsuarios();
    }//GEN-LAST:event_btnPesquisarUsuarioMouseClicked

    private void btnFavoritarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFavoritarMouseClicked
        new Politicos(null).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFavoritarMouseClicked

    private void txtIdeologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdeologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdeologiaActionPerformed

    private void tblDeputado4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeputado4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDeputado4MouseClicked

    private void btnPesquisarDeputado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarDeputado4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarDeputado4ActionPerformed

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        boolean certo = true;
        try {

            usuario.setNome(txtNome.getText());
            usuario.setCpf(txtCPF.getText());
            usuario.setEmail(txtEmail.getText());
            usuario.setIdeologia(txtIdeologia.getText());

            BancoUsuarios bd = new BancoUsuarios(usuario);

            bd.connect();
            bd.alterar();
            bd.disconnect();
        } catch (Exception erro) {
            certo = false;
            JOptionPane.showMessageDialog(null,
                    "Um erro ocorreu: " + erro);
        } finally {
            if (certo) {
                JOptionPane.showMessageDialog(null,
                        "Alteração Salva com Sucesso ");
            }
        }
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        boolean certo = true;
        try {

            BancoUsuarios bd = new BancoUsuarios(usuario);

            bd.connect();
            bd.excluir();
            bd.disconnect();
        } catch (Exception erro) {
            certo = false;
            JOptionPane.showMessageDialog(null,
                    "Um erro ocorreu: " + erro);
        } finally {
            if (certo) {
                JOptionPane.showMessageDialog(null,
                        "Excluido com Sucesso ");
                new Login().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnLogin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin5MouseClicked

    private void btnLogin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin4MouseClicked

    private void btnPesquisarDeputado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarDeputado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarDeputado3ActionPerformed

    private void tblDeputado3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeputado3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDeputado3MouseClicked

    private void txtNome13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome13ActionPerformed

    private void btnLogin8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin8MouseClicked

    private void btnMudarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMudarSenhaMouseClicked
        // TODO add your handling code here:
        new AlterarSenha(usuario).setVisible(true);

    }//GEN-LAST:event_btnMudarSenhaMouseClicked

    private void btnPesquisarDeputado4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarDeputado4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarDeputado4MouseClicked

    // troca a cor dos botões
    public List<Deputado> todos_deputados;
    public boolean first_load = true;

    private void imprimirSelecao(String id) throws JSONException {
        ImageIcon image = null;

        System.out.println(id);
        Deputado dep = Capi.pesquisaDeputadoEspecifico(id);
        List<Discurso> x = Capi.mostraDiscursos(id);
        titulo.setText(dep.getNome());
        subtitulo.setText(dep.getId());
        lblUf.setText(dep.getSiglaUf());
        lblEmail.setText(dep.getEmail());
        lblPartido.setText(dep.getSiglaPartido());
        lblCidade.setText(dep.getMunicipioNascimento());
        lblCpf.setText(dep.getCpf());
        lblEscolaridade.setText(dep.getEscolaridade());
        lblIL.setText(dep.getIdLegislatura());
        try {
            URL url = new URL(dep.getUrlFoto());
            image = new ImageIcon(url, "a");
        } catch (MalformedURLException e) {
            System.out.println(e);
        }
        // ImageIcon img = new ImageIcon();
        lblImg.setIcon(image);
        if (x.isEmpty()) {
            txtDiscurso.append("nenhum discurso!!!");
        } else {

            for (int i = 0; i < x.size(); i++) {
                txtDiscurso.append("\nTitulo: " + x.get(i).getTitulo() + "\nTipo de discurso: " + x.get(i).getTipoDiscurso() + "\n\n" + x.get(i).getTranscricao() + "\n\n");
            }
        }
    }

    public void imprimirMinhaConta() {
        BancoUsuarios banco = new BancoUsuarios();
        //   Usuario user = banco.procura();
        banco.connect();
        // txtNome.setText();
        banco.disconnect();
    }

    public void setLblColor(JLabel lbl) {
        lbl.setBackground(new Color(0, 204, 204));
    }

    public void limpaTela() {
        Deputados.setVisible(false);
        Usuarios.setVisible(false);
        MinhaConta.setVisible(false);
        MostraDeputado.setVisible(false);
        MostraUsuario.setVisible(false);
    }

    public void resetLblColor(JLabel lbl) {
        lbl.setBackground(new Color(0, 153, 153));
    }

    private void imprimirDeputados(String pesquisa) throws JSONException {
        if (this.first_load) {
            this.todos_deputados = Capi.mostraDeputados();
            this.first_load = false;
        }
        DefaultTableModel model = (DefaultTableModel) tblDeputado.getModel();

        model.setRowCount(0);
        List<Deputado> y = null;
        if (jRadioButton1.isSelected()) {
            y = Capi.pesquisaDeputados("nome", pesquisa, this.todos_deputados);
        }
        if (jRadioButton2.isSelected()) {
            y = Capi.pesquisaDeputados("id", pesquisa, this.todos_deputados);
        }
        if (jRadioButton3.isSelected()) {
            y = Capi.pesquisaDeputados("partido", pesquisa, this.todos_deputados);
        }
        String rowData[] = new String[4];
        for (int x = 0; x < y.size(); x++) {
            rowData[0] = y.get(x).getId();
            rowData[1] = y.get(x).getNome();
            rowData[2] = y.get(x).getSiglaPartido();
            rowData[3] = y.get(x).getSiglaUf();
            model.addRow(rowData);
        }
    }

    private void imprimirUsuarios() {
        BancoUsuarios banco = new BancoUsuarios();
        banco.connect();
        List<Usuario> u = banco.pegaDados();
        DefaultTableModel model = (DefaultTableModel) tblUsuario.getModel();
        String rowData[] = new String[4];
        model.setRowCount(0);
        for (int x = 0; x < u.size(); x++) {
            if (u.get(x).getStatus() == 1) {
                rowData[0] = u.get(x).getIdUsuario();
                rowData[1] = u.get(x).getNome();
                rowData[2] = u.get(x).getCpf();
                rowData[3] = u.get(x).getSenha();
                model.addRow(rowData);
            }

        }
    }

    private void incluirUsuario() {

    }

    private void excluirUsuario() {

    }
    //-----------End --------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //Change UI look of table.
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Politicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Politicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Politicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Politicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Politicos(null).setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Deputados;
    private javax.swing.JPanel MinhaConta;
    private javax.swing.JPanel MostraDeputado;
    private javax.swing.JPanel MostraUsuario;
    private javax.swing.JPanel Principal;
    private javax.swing.JPanel Usuarios;
    private javax.swing.JPanel body_mostradeputado;
    private javax.swing.JPanel body_mostradeputado4;
    private javax.swing.JPanel body_mostradeputado5;
    private javax.swing.JPanel body_pesquisa;
    private javax.swing.JLabel btnAlterar;
    private javax.swing.JLabel btnExcluir;
    private javax.swing.JLabel btnFavoritar;
    private javax.swing.JLabel btnLogin4;
    private javax.swing.JLabel btnLogin5;
    private javax.swing.JLabel btnLogin8;
    private javax.swing.JLabel btnMinhaConta;
    private javax.swing.JLabel btnMudarSenha;
    private javax.swing.JLabel btnPesquisa;
    private javax.swing.JButton btnPesquisarDeputado;
    private javax.swing.JButton btnPesquisarDeputado3;
    private javax.swing.JButton btnPesquisarDeputado4;
    private javax.swing.JButton btnPesquisarUsuario;
    private javax.swing.JLabel btnUsuarios;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail4;
    private javax.swing.JLabel lblEmail5;
    private javax.swing.JLabel lblEscolaridade;
    private javax.swing.JLabel lblIL;
    private javax.swing.JLabel lblIL4;
    private javax.swing.JLabel lblIL5;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPartido;
    private javax.swing.JLabel lblUf;
    private javax.swing.JPanel main;
    private javax.swing.ButtonGroup radPesquisa;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JTable tblDeputado;
    private javax.swing.JTable tblDeputado3;
    private javax.swing.JTable tblDeputado4;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextArea txtDiscurso;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdeologia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome10;
    private javax.swing.JTextField txtNome11;
    private javax.swing.JTextField txtNome13;
    private javax.swing.JTextField txtNome14;
    // End of variables declaration//GEN-END:variables
}
